commi

diff --git a/docker/dockerfiles/Dockerfile.bedrock-init b/docker/dockerfiles/Dockerfile.bedrock-init
--- a/docker/dockerfiles/Dockerfile.bedrock-init
+++ b/docker/dockerfiles/Dockerfile.bedrock-init
@@ -7,10 +7,11 @@ ARG DEBIAN_FRONTEND=noninteractive
 ENV APT_LISTCHANGES_FRONTEND=none \
     DEBIAN_FRONTEND=noninteractive
 
-# Update package list and upgrade if necessary, also output the process logs
-RUN apt-get update -y && apt-get upgrade -y || { echo "apt-get update/upgrade failed"; exit 1; } \
-    && apt-get install -y curl wget git rsync build-essential openssl python3 python3-pip aria2 zstd lz4 || { echo "apt-get install failed"; exit 1; } \
-    && rm -rf /var/lib/apt/lists/*  # Clean up apt cache
+# Update and upgrade packages, and log output for troubleshooting
+RUN apt-get update -y && apt-get upgrade -y && \
+    apt-get install -y curl wget git rsync build-essential openssl python3 python3-pip aria2 zstd lz4 || \
+    (echo "apt-get update/upgrade or install failed"; tail -n 10 /var/log/apt/term.log; exit 1) && \
+    rm -rf /var/lib/apt/lists/*  # Clean up apt cache
 
 # Install Go.
 RUN curl -sSL https://golang.org/dl/go1.21.6.linux-amd64.tar.gz | tar -v -C /usr/local -xz
